version: '1'
name: 'flex-users-compose-dev'

services:
  db:
    container_name: 'flex_users_db'
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=flex_users
      - POSTGRES_PASSWORD=flex_users
      - POSTGRES_DB=flex_users