version: '1'
name: 'flex-users-compose'

services:
  db:
    container_name: 'flex_users_db'
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=flex_users
      - POSTGRES_PASSWORD=flex_users
      - POSTGRES_DB=flex_users
  flex_users:
  # diz pra buildar a imagem local e rodar
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://db:5432/flex_users
      - DATASOURCE_USER=flex_users
      - DATASOURCE_PASSWORD=flex_users